# Use root/root as user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: web_shop_db

    ports:
      - "5432:5432"