spring:
  application:
    alias: WEBSHOP
    version: '@project.version@'
  main:
    banner-mode: OFF
  datasource:
    database: web_shop_db
    db-schema: web_shop_schema
    url: "jdbc:postgresql://localhost:5432/${spring.datasource.database}"
    username: admin
    password: admin
    hikari:
      pool-name: postgres-local
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        default_schema: ${spring.datasource.db-schema}
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        types.print.banner: false
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    enabled: true
    schemas: ${spring.datasource.db-schema}